### ISSUE TITLE
Module import issue

### ISSUE THREAD

**Issue by MagneticsRF** [argilo/gr-tenna#1]
Hello, 

Cool tool, I am trying to get it up and running, this is the error it throws, only change made was I set the default to the hackrf instead of the usrp. 

```
Traceback (most recent call last):
  File "gotenna.py", line 54, in <module>
    tb = gotenna_rx_hackrf()
  File "/home/ubuntu/Desktop/gr-tenna/gotenna_rx_hackrf.py", line 63, in __init__
    self.digital_symbol_sync_xx_0 = digital.symbol_sync_ff(digital.TED_DANDREA_AND_MENGALI_GEN_MSK, float(chan_spacing) / baud_rate / 4, 0.05, 1.5, 1.0, 0.001 * float(chan_spacing) / baud_rate / 4, 1, digital.constellation_bpsk().base(), digital.IR_MMSE_8TAP, 128, ([]))
AttributeError: 'module' object has no attribute 'symbol_sync_ff'
```

So trying to fix this my self, I went and looked for the symbol_sync_ff module for python in the gnuradio/digital but there isn't one, but there is a c++ file for symbol_sync_ff. 

I'm unsure if this is suppose to be built on the GNU 3.8? 

Also, to avoid double posting a question about the variables, 

```
DATA_CHANNELS = [
    923500000, 923000000, 925500000, 926500000, 925000000, 908000000, 911500000, 905500000,
    903500000, 915500000, 909000000, 912000000, 922000000, 921000000, 924000000, 907500000,
    910000000, 912500000, 927500000, 910500000, 913000000, 918500000, 913500000, 914000000,
    902500000, 922500000, 907000000, 920000000, 919000000, 916500000, 919500000, 914500000,
    918000000, 911000000, 917500000, 916000000, 924500000, 909500000, 904500000, 904000000,
    917000000, 921500000, 920500000, 905000000, 908500000, 906500000, 926000000, 906000000
]

```

Would this be the hop table being referenced by the spec sheet for the gotenna radio 
[spec sheet for silicon labs si4460](https://www.silabs.com/documents/public/data-sheets/Si4464-63-61-60.pdf)
```
5.3.1.2.  Automatic RX Hopping and Hop Table
The  transceiver  supports  an  automatic  hopping  feature  
that  can  be  fully  configured  through  the  API.  This  is
intended  for  RX  hopping  where  the  device  has  to  hop  from  channel  to  channel  and  look  for  packets.  Once  the
device is put into the RX state, it 
automatically starts hopping through th
e hop table if the feature is enabled.
The hop table can hold up to 64 entries and is maintained in firmware
```

**Comment by argilo** [comment]
> I'm unsure if this is suppose to be built on the GNU 3.8?

I recently added support for GNU Radio 3.8. I'd suggest building GNU Radio and gr-tenna using the maint-3.8 branches if you'd like to go that route.

> Would this be the hop table being referenced by the spec sheet

It's the hop sequence that is used for data packets (but not for control packets, which have three dedicated channels). I wouldn't be surprised if the automatic hopping feature in the si4460 is used, but I don't know for sure.

**Comment by argilo** [comment]
I'll close off this issue for now, since the problem seems to have been lack of support for GNU Radio 3.8, which has now been resolved. If you're still having trouble, please let me know and I'll re-open the issue.
