### ISSUE TITLE
Question about use of chan_spacing vs samp_rate

### ISSUE THREAD

**Issue by sybip** [argilo/gr-tenna#4]
Hi, I'm not sure if this is a real issue or just my lack of understanding, but at a few points in the flow I noticed the use of the `chan_spacing` variable where I was expecting `samp_rate`. Specifically, in the parameters for the **Quadrature Demod** and the **Symbol Sync** blocks:

https://github.com/argilo/gr-tenna/blob/1a29292a68d7807c15c9386bf0b11ac190472783/gotenna_rx_hackrf.grc#L89

https://github.com/argilo/gr-tenna/blob/1a29292a68d7807c15c9386bf0b11ac190472783/gotenna_rx_hackrf.grc#L141

https://github.com/argilo/gr-tenna/blob/1a29292a68d7807c15c9386bf0b11ac190472783/gotenna_rx_hackrf.grc#L148

I realize that they are numerically equal by default, and both set to 500k (Hz | sps). However, from a functional perspective they are different parameters that can be varied independently.

Is the use of `chan_spacing` correct in these cases, or should it be `samp_rate` instead?

**Comment by argilo** [comment]
Sorry for the late reply.

I suppose `chan_spacing` is not the best variable name, since it's being used as a sample rate, but it is the correct value to use since `samp_rate` is the input sample rate, which may be higher than 500k.
